# Generated by Django 3.0.6 on 2020-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_exchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='bookTicker_endpoint',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exchanges',
            name='exchange_img_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
