# Generated by Django 3.0.6 on 2020-06-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200622_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='price_endpoint',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='exchanges',
            name='bookTicker_endpoint',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='exchanges',
            name='exchange_img_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
