# Generated by Django 3.0.6 on 2020-06-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200622_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanges',
            old_name='exchange_id',
            new_name='exchange_name',
        ),
    ]
