# Generated by Django 3.0.6 on 2020-06-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200623_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='is_all_coins',
            field=models.BooleanField(default=True),
        ),
    ]
