# Generated by Django 3.0.6 on 2020-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_exchanges_is_all_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='symbols_endpoint',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
