# Generated by Django 3.0.6 on 2020-06-23 17:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_exchanges_symbols_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='price_datatype',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
