# Generated by Django 3.0.6 on 2020-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_exchanges_price_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='has_usdt',
            field=models.BooleanField(default=True),
        ),
    ]
