# Generated by Django 3.0.6 on 2020-06-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_exchanges_symbol_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='symbol_format',
            field=models.CharField(default='{symbol}', max_length=360),
        ),
    ]
